[package]
name = "avatar"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
gpui = "0.2.2"
nanoid = "0.4.0"
rand = "0.9.2"
rfd = "0.15.4"
strum = { version = "0.27.2", features = ["derive"] }
